// Generated by dev/gallery/package.py; do not edit by hand.
window.GALLERY = [
 {
  "name": "bd",
  "folder": "00_datasets",
  "title": "Build",
  "use": "Cuts a study's dataset from a master snapshot: cohort list, exclusions with attrition and derived variables, then a dated release registered as the study dataset.",
  "deprecated_by": null,
  "call": "add_job(\"bd\", subject = \"study\", type = \"build\")",
  "tables": 0,
  "figures": 0,
  "seconds": null,
  "report": false,
  "issues": [],
  "note": ""
 },
 {
  "name": "dc-general",
  "folder": "10_descriptive",
  "title": "Descriptive: general",
  "use": "First look at a built cohort: what the data contain, how each categorical variable breaks down, how each continuous variable is distributed, and which variables move together.",
  "deprecated_by": null,
  "call": "add_job(\"dc.general\", subject = \"cohort\", type = \"eda\")",
  "tables": 14,
  "figures": 0,
  "seconds": 5.1,
  "report": true,
  "issues": [],
  "note": ""
 },
 {
  "name": "dc-gfup",
  "folder": "10_descriptive",
  "title": "Descriptive: follow-up",
  "use": "Checks follow-up before any time-related analysis: counts for the cohort, the event and censored subsets, and the missing, negative and zero intervals, then the goodness-of-follow-up figure, each patient's follow-up against operation year under the diagonal the close date allows.",
  "deprecated_by": null,
  "call": "add_job(\"dc.gfup\", subject = \"cohort\", type = \"eda\")",
  "tables": 4,
  "figures": 1,
  "seconds": 5.8,
  "report": true,
  "issues": [],
  "note": ""
 },
 {
  "name": "dc-stddiff",
  "folder": "10_descriptive",
  "title": "Descriptive: standardized differences",
  "use": "The balance table: the standardized difference of each baseline variable between two groups, unadjusted and, when the study has them, in the matched set and under matching weights, with an optional permutation reference.",
  "deprecated_by": null,
  "call": "add_job(\"dc.stddiff\", subject = \"cohort\", type = \"balance\")",
  "tables": 5,
  "figures": 1,
  "seconds": 6.2,
  "report": true,
  "issues": [],
  "note": ""
 },
 {
  "name": "dc-tables",
  "folder": "10_descriptive",
  "title": "Descriptive: formatted tables",
  "use": "The formatted descriptive table: every reported variable under its section heading, categorical as n (%) and continuous as the summary you choose, written to Word.",
  "deprecated_by": null,
  "call": "add_job(\"dc.tables\", subject = \"cohort\", type = \"eda\")",
  "tables": 2,
  "figures": 0,
  "seconds": 7.1,
  "report": true,
  "issues": [],
  "note": "The session asked whether this should become a named Table 1 job."
 },
 {
  "name": "dp-eda",
  "folder": "10_descriptive",
  "title": "Descriptive plot: EDA report",
  "use": "The whole data-checking report in one render: every column's contents, goodness of follow-up, then continuous variables and categorical variables as percentages and counts, each section with its table.",
  "deprecated_by": null,
  "call": "add_job(\"dp.eda\", subject = \"cohort\", type = \"eda\")",
  "tables": 6,
  "figures": 7,
  "seconds": 13.1,
  "report": true,
  "issues": [],
  "note": "No grouping variable, which the legacy EDA report had."
 },
 {
  "name": "ac",
  "folder": "20_distributions",
  "title": "Actuarial",
  "use": "Nonparametric life tables by stratum, with estimates at the reporting horizons.",
  "deprecated_by": null,
  "call": "add_job(\"ac\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 8,
  "figures": 0,
  "seconds": 5.2,
  "report": true,
  "issues": [
   177,
   172
  ],
  "note": ""
 },
 {
  "name": "hz",
  "folder": "20_distributions",
  "title": "Hazard fit",
  "use": "Fits and saves the multiphase parametric hazard model whose shape the later hm, hp and hs jobs read.",
  "deprecated_by": null,
  "call": "add_job(\"hz\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 8,
  "figures": 0,
  "seconds": 8.0,
  "report": true,
  "issues": [
   169,
   175,
   172
  ],
  "note": ""
 },
 {
  "name": "bc",
  "folder": "30_analyses",
  "title": "Bootstrap Cox",
  "use": "Bootstrap variable-selection screen over a Cox proportional hazards model.",
  "deprecated_by": null,
  "call": "add_job(\"bc\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 2,
  "figures": 1,
  "seconds": 13.8,
  "report": true,
  "issues": [
   185,
   186,
   188,
   189
  ],
  "note": "Age stands in as the forced base term, so it has no frequency row."
 },
 {
  "name": "bh",
  "folder": "30_analyses",
  "title": "Bootstrap hazard",
  "use": "Bootstrap variable-selection screen for a hazard model: how often each candidate survives, and which to carry into hm.",
  "deprecated_by": null,
  "call": "add_job(\"bh\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 2,
  "figures": 1,
  "seconds": 116.7,
  "report": true,
  "issues": [
   185,
   187,
   188,
   189,
   175
  ],
  "note": "8 replicates; the early phase is under-sampled."
 },
 {
  "name": "bl",
  "folder": "30_analyses",
  "title": "Bootstrap logistic",
  "use": "Bootstrap variable-selection screen over a logistic model.",
  "deprecated_by": null,
  "call": "add_job(\"bl\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 2,
  "figures": 1,
  "seconds": 18.2,
  "report": true,
  "issues": [
   185,
   188,
   189
  ],
  "note": "BMI reaches 65% and is retained though it drives nothing."
 },
 {
  "name": "br",
  "folder": "30_analyses",
  "title": "Bootstrap regression",
  "use": "Bootstrap variable-selection screen over a linear model.",
  "deprecated_by": null,
  "call": "add_job(\"br\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 2,
  "figures": 1,
  "seconds": 8.8,
  "report": true,
  "issues": [
   185,
   188,
   189
  ],
  "note": ""
 },
 {
  "name": "hm",
  "folder": "30_analyses",
  "title": "Hazard model",
  "use": "Multivariable risk-factor model built on the shape parameters the hz job fitted.",
  "deprecated_by": null,
  "call": "add_job(\"hm\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 12,
  "figures": 0,
  "seconds": 7.2,
  "report": true,
  "issues": [
   228,
   170,
   171,
   174,
   178,
   176
  ],
  "note": "Stage 1 fixes nothing, so the two-stage table compares one model with itself."
 },
 {
  "name": "lm-balancing_count",
  "folder": "30_analyses",
  "title": "Logistic model: count balancing score",
  "use": "Poisson or negative-binomial balancing score for a count exposure, with the distribution as a reviewed study choice.",
  "deprecated_by": null,
  "call": "add_job(\"lm.balancing_count\", subject = \"exposure\", type = \"balancing\")",
  "tables": 5,
  "figures": 0,
  "seconds": 4.9,
  "report": true,
  "issues": [
   179,
   174
  ],
  "note": "The rate ratio column is labelled odds_ratio (hvtiRpropensity#46)."
 },
 {
  "name": "lm-binary",
  "folder": "30_analyses",
  "title": "Logistic model: binary outcome",
  "use": "Binary outcome logistic model, saving the fitted model, predictions and pooled inference across imputations.",
  "deprecated_by": null,
  "call": "add_job(\"lm.binary\", subject = \"outcome\", type = \"analysis\")",
  "tables": 4,
  "figures": 0,
  "seconds": 4.7,
  "report": true,
  "issues": [
   179,
   174
  ],
  "note": ""
 },
 {
  "name": "lm-checkpred",
  "folder": "30_analyses",
  "title": "Logistic model: validate saved predictions",
  "use": "Applies a saved lm-binary model to a validation cohort.",
  "deprecated_by": null,
  "call": "add_job(\"lm.checkpred\", subject = \"outcome\", type = \"analysis\")",
  "tables": 3,
  "figures": 0,
  "seconds": 4.7,
  "report": true,
  "issues": [
   180,
   179
  ],
  "note": "AUC 0.75 and observed/expected 1.16 on the 2015-onward cohort."
 },
 {
  "name": "lm-nominal",
  "folder": "30_analyses",
  "title": "Logistic model: nominal outcome",
  "use": "Generalized-logit model for a nominal outcome with a declared level set and reference.",
  "deprecated_by": null,
  "call": "add_job(\"lm.nominal\", subject = \"outcome\", type = \"analysis\")",
  "tables": 4,
  "figures": 0,
  "seconds": 4.9,
  "report": true,
  "issues": [
   179,
   174
  ],
  "note": ""
 },
 {
  "name": "lm-ordinal",
  "folder": "30_analyses",
  "title": "Logistic model: ordinal outcome",
  "use": "Proportional-odds model for an ordered outcome whose full order is declared, not inferred.",
  "deprecated_by": null,
  "call": "add_job(\"lm.ordinal\", subject = \"outcome\", type = \"analysis\")",
  "tables": 4,
  "figures": 0,
  "seconds": 4.8,
  "report": true,
  "issues": [
   179,
   174
  ],
  "note": ""
 },
 {
  "name": "lm-propensity_binary",
  "folder": "30_analyses",
  "title": "Logistic model: binary propensity score",
  "use": "Propensity model for a binary treatment, scoring the columns that matching and weighting jobs use.",
  "deprecated_by": null,
  "call": "add_job(\"lm.propensity_binary\", subject = \"treatment\", type = \"propensity\")",
  "tables": 6,
  "figures": 0,
  "seconds": 4.8,
  "report": true,
  "issues": [
   179,
   174
  ],
  "note": "Group counts print as control and treated, not the declared levels (hvtiRpropensity#47)."
 },
 {
  "name": "lm-propensity_nominal",
  "folder": "30_analyses",
  "title": "Logistic model: nominal propensity score",
  "use": "Generalized-logit propensity model for a nominal treatment with an explicit reference level.",
  "deprecated_by": null,
  "call": "add_job(\"lm.propensity_nominal\", subject = \"treatment\", type = \"propensity\")",
  "tables": 5,
  "figures": 0,
  "seconds": 4.8,
  "report": true,
  "issues": [
   191,
   179,
   174
  ],
  "note": "No balance table, unlike the binary job."
 },
 {
  "name": "lm-propensity_ordinal",
  "folder": "30_analyses",
  "title": "Logistic model: ordinal propensity score",
  "use": "Proportional-odds propensity model for an ordered treatment.",
  "deprecated_by": null,
  "call": "add_job(\"lm.propensity_ordinal\", subject = \"treatment\", type = \"propensity\")",
  "tables": 7,
  "figures": 0,
  "seconds": 4.9,
  "report": true,
  "issues": [
   191,
   179,
   174
  ],
  "note": "No balance table, unlike the binary job."
 },
 {
  "name": "nb-boostmtree",
  "folder": "30_analyses",
  "title": "Boosting: boostmtree",
  "use": "Fits boosted multivariate trees to a response measured repeatedly over follow-up, and reports its error path, fit over time, importance, partial effects and patient trajectories.",
  "deprecated_by": null,
  "call": "add_job(\"nb.boostmtree\", subject = \"lvef\", type = \"boost\")",
  "tables": 3,
  "figures": 6,
  "seconds": 310.0,
  "report": true,
  "issues": [],
  "note": "Reads a synthetic echo series, 300 patients with 2 to 6 visits; M = 200, so it is the slowest job here."
 },
 {
  "name": "rfc-explain",
  "folder": "30_analyses",
  "title": "Random forest classifier: explain",
  "use": "Explains a saved classification forest: variable importance, VarPro and dependence plots.",
  "deprecated_by": null,
  "call": "add_job(\"rfc.explain\", subject = \"dead\", type = \"rfc\")",
  "tables": 2,
  "figures": 5,
  "seconds": 21.9,
  "report": true,
  "issues": [
   166,
   167
  ],
  "note": "Partial-dependence bars for 0/1 predictors are on the wrong scale (ggRandomForests#299)."
 },
 {
  "name": "rfc-fit",
  "folder": "30_analyses",
  "title": "Random forest classifier: fit",
  "use": "Grows a classification forest and checks it: out-of-bag error and the ROC curve with its AUC.",
  "deprecated_by": null,
  "call": "add_job(\"rfc.fit\", subject = \"dead\", type = \"rfc\")",
  "tables": 1,
  "figures": 2,
  "seconds": 9.3,
  "report": true,
  "issues": [
   165,
   181,
   182
  ],
  "note": ""
 },
 {
  "name": "rfr-explain",
  "folder": "30_analyses",
  "title": "Random forest regression: explain",
  "use": "Explains a saved regression forest: variable importance, VarPro and dependence plots.",
  "deprecated_by": null,
  "call": "add_job(\"rfr.explain\", subject = \"los\", type = \"rfr\")",
  "tables": 2,
  "figures": 5,
  "seconds": 22.5,
  "report": true,
  "issues": [
   166,
   167
  ],
  "note": ""
 },
 {
  "name": "rfr-fit",
  "folder": "30_analyses",
  "title": "Random forest regression: fit",
  "use": "Grows a regression forest and checks it: out-of-bag error and predicted against observed.",
  "deprecated_by": null,
  "call": "add_job(\"rfr.fit\", subject = \"los\", type = \"rfr\")",
  "tables": 1,
  "figures": 2,
  "seconds": 8.6,
  "report": true,
  "issues": [
   165,
   181,
   182
  ],
  "note": ""
 },
 {
  "name": "rfs-explain",
  "folder": "30_analyses",
  "title": "Random forest survival: explain",
  "use": "Explains a saved survival forest: variable importance, VarPro and dependence plots.",
  "deprecated_by": null,
  "call": "add_job(\"rfs.explain\", subject = \"dead\", type = \"rfs\")",
  "tables": 2,
  "figures": 5,
  "seconds": 107.9,
  "report": true,
  "issues": [
   166,
   167
  ],
  "note": "Partial-dependence bars for 0/1 predictors are on the wrong scale (ggRandomForests#299)."
 },
 {
  "name": "rfs-fit",
  "folder": "30_analyses",
  "title": "Random forest survival: fit",
  "use": "Grows a random survival forest and checks it learned something: out-of-bag error, predicted survival and the Brier score.",
  "deprecated_by": null,
  "call": "add_job(\"rfs.fit\", subject = \"dead\", type = \"rfs\")",
  "tables": 1,
  "figures": 3,
  "seconds": 12.8,
  "report": true,
  "issues": [
   165,
   181,
   182
  ],
  "note": ""
 },
 {
  "name": "dp-gfup",
  "folder": "40_graphs",
  "title": "Descriptive plot: follow-up",
  "use": "Deprecated in favor of dc-gfup, which draws the same figure beside its follow-up tables.",
  "deprecated_by": "dc-gfup",
  "call": "add_job(\"dp.gfup\", subject = \"cohort\", type = \"eda\")",
  "tables": 2,
  "figures": 2,
  "seconds": 5.8,
  "report": true,
  "issues": [],
  "note": ""
 },
 {
  "name": "dp-trends",
  "folder": "40_graphs",
  "title": "Descriptive plot: trends",
  "use": "How the cohort changed over the years of operation: the share with a characteristic, or the level of a measurement, year by year with a smooth.",
  "deprecated_by": null,
  "call": "add_job(\"dp.trends\", subject = \"cohort\", type = \"eda\")",
  "tables": 2,
  "figures": 4,
  "seconds": 6.4,
  "report": true,
  "issues": [],
  "note": ""
 },
 {
  "name": "hp",
  "folder": "40_graphs",
  "title": "Hazard plot",
  "use": "Nomogram and hazard figures, read from the ac life table and the hz fit rather than recomputed.",
  "deprecated_by": null,
  "call": "add_job(\"hp\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 4,
  "figures": 3,
  "seconds": 5.5,
  "report": true,
  "issues": [
   177,
   176
  ],
  "note": ""
 },
 {
  "name": "hs-concordance",
  "folder": "40_graphs",
  "title": "Hazard concordance",
  "use": "Every patient predicted through every treatment group's hm model at one horizon, with an optional table of actual against best-predicted treatment.",
  "deprecated_by": null,
  "call": "add_job(\"hs.concordance\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 7,
  "figures": 0,
  "seconds": 33.5,
  "report": true,
  "issues": [
   227,
   228
  ],
  "note": "Reads one model per approach group, each fitted by an hz and hm rendered for it; render time includes those four jobs. The group models screen three candidates: with the chain's five, the surgical group's fit has no variance matrix and this job stops (#227)."
 },
 {
  "name": "hs-setup",
  "folder": "40_graphs",
  "title": "Hazard setup",
  "use": "Patient-level predictions from the hm model, set against the survival of a matched general population.",
  "deprecated_by": null,
  "call": "add_job(\"hs.setup\", subject = \"dead_pa\", type = \"hz\")",
  "tables": 4,
  "figures": 0,
  "seconds": 5.3,
  "report": true,
  "issues": [
   183,
   177
  ],
  "note": "Needs hand-derived 0/1 sex and race columns."
 }
];
window.GALLERY_BUILT = "1.3.0 \u00b7 built 2026-10-09";
